version: "3.3"
services:
  grape-app:
    build: .
    ports:
      - "8080:8080"
  pg-database:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
